version: '3.8'

services:
  station:
    image: ghcr.io/filecoin-station/core:latest
    container_name: station
    environment:
      - FIL_WALLET_ADDRESS=0x721bc9128e2d437eF874400D74346E538fa7D2E6
    volumes:
      - ./state:/home/node/.local/state/
    command: ["node", "start"]
