version: '3.8'

services:
  my-gotty:
    build: .
    container_name: my-gotty
    hostname: mygotty
    ports:
      - 8989:8080
    tty: true
    stdin_open: true
    volumes:
      - ./state:/home/node/.local/state
    environment:
      - FIL_WALLET_ADDRESS=0x721bc9128e2d437eF874400D74346E538fa7D2E6
    command: /bin/bash /run_gotty.sh
