version: '3.8'
services:
  station:
    image: ghcr.io/filecoin-station/core:latest
    container_name: station
    environment:
      - FIL_WALLET_ADDRESS=f410fm2ouuqhnnpu2tu4gm7plm63fcdcmujwsfdpouca
      - PORT=10000
      - PASSPHRASE=rule notable diary rally enact mimic mixture various display burst trouble resource
    volumes:
      - ./state:/home/node/.local/state/ 
      - ./server.log:/home/node/server.log  
    ports:
      - "10000:10000"  # Mapea el puerto del contenedor al host
    command: ["sh", "-c", "node server.js & station >> /home/node/server.log 2>&1"]  
